commerce_payment.commerce_payment_gateway.plugin.partpay:
  type: commerce_payment_gateway_configuration
  mapping:
    partpayClientId:
      type: string
      label: 'Client Id'
    partpaySecret:
      type: string
      label: 'Secret'
    partpayRef:
      type: string
      label: 'Merchant Reference Prefix'
